version: "3"

services:
  app:
    build: .
    container_name: app
    command: dockerize -wait tcp://superagro_app:queenoftheskiesb747@superagro_db:5432/postgres -timeout 40s -template ./.docker/.env.template:.env ./.docker/entrypoint.sh
    environment:
      - PORT=3001
      - DB_HOST=superagro_db
      - DB_USER=superagro_app
      - DB_PASSWORD=queenoftheskiesb747
      - DB_NAME=superagro_db
    volumes:
      - .:/superagroapp
    ports:
      - 3001:3001
    networks:
      - superagro-networks
    depends_on:
      - superagro_db

  superagro_db:
    image: postgres
    container_name: superagro_db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    networks:
      - superagro-networks
    environment:
      - POSTGRES_USER=superagro_app
      - POSTGRES_PASSWORD=queenoftheskiesb747
    ports:
      - "5432:5432"

networks:
  superagro-networks:
    driver: bridge
